import React, { useCallback, useMemo, useRef } from 'react'

const BuilderCard = ({ imagePreview, name, role, title, className = '' }) => {
  const cardRef = useRef(null); const glareRef = useRef(null)
  const serial = useMemo(() => `HHG-2026-${String((name || 'GOA').split('').reduce((total, char) => total + char.charCodeAt(0), 247) % 9999).padStart(4, '0')}`, [name])
  const tilt = useCallback(event => { const card = cardRef.current; if (!card) return; const rect = card.getBoundingClientRect(); const x = (event.clientX - rect.left) / rect.width; const y = (event.clientY - rect.top) / rect.height; const rx = (0.5 - y) * 12; const ry = (x - 0.5) * 12; card.style.transition = 'transform 80ms linear, box-shadow 80ms linear'; card.style.transform = `perspective(900px) rotateX(${rx}deg) rotateY(${ry}deg) translateZ(8px)`; card.style.boxShadow = `${-ry}px ${rx + 14}px 24px rgba(0, 20, 10, .48)`; if (glareRef.current) { glareRef.current.style.opacity = '1'; glareRef.current.style.background = `radial-gradient(circle at ${x * 100}% ${y * 100}%, rgba(255,255,255,.3), transparent 38%)` } }, [])
  const reset = useCallback(() => { const card = cardRef.current; if (!card) return; card.style.transition = 'transform 420ms cubic-bezier(.2,.8,.2,1), box-shadow 420ms ease'; card.style.transform = 'perspective(900px) rotateX(0) rotateY(0) translateZ(0)'; card.style.boxShadow = '8px 10px 0 rgba(0,38,21,.35)'; if (glareRef.current) glareRef.current.style.opacity = '0' }, [])
  return <article ref={cardRef} onPointerMove={tilt} onPointerLeave={reset} onPointerUp={reset} onPointerCancel={reset} onPointerDown={event => event.currentTarget.setPointerCapture?.(event.pointerId)} onBlur={reset} tabIndex="0" className={`builder-card builder-card-3d relative aspect-[4/5] overflow-hidden border-2 border-yellow-300 bg-[#004b2c] ${className}`} aria-label="HH Goa Builder Pass preview. Move or drag to tilt.">
    <div className="absolute inset-0 opacity-30 hh-grid" />
    <div className="pointer-events-none absolute inset-[1.3cqw] border border-pink-500/80" />
    <div className="absolute left-[6%] right-[6%] top-[4%] border-b border-yellow-300/60 pb-[3%] text-center"><p className="hh-mono text-[2.4cqw] font-bold tracking-[.4em] text-yellow-200">BUILDER PASS</p><span className="absolute right-0 top-0 hh-mono text-[2.1cqw] font-black text-yellow-300">2:47<br />STUDIO</span><h2 className="mt-[1%] font-sans text-[7cqw] font-black leading-none tracking-[.13em] text-yellow-300">HACKER <span className="hh-pink font-serif tracking-[-.1em]">गोवा</span> HOUSE</h2><p className="mt-[2%] hh-mono text-[2.4cqw] text-yellow-200">GOA, INDIA · 28—31 OCT 2026</p></div>
    <div className="absolute left-[14%] right-[14%] top-[22%] aspect-square border-[1.4cqw] border-pink-500 bg-yellow-300 p-[1.4cqw] shadow-[.8cqw_.8cqw_0_#ffe11a]"><i className="absolute left-[2.6cqw] top-[2.6cqw] z-10 h-[6cqw] w-[6cqw] border-l-[.7cqw] border-t-[.7cqw] border-[#005c35]" /><i className="absolute right-[2.6cqw] top-[2.6cqw] z-10 h-[6cqw] w-[6cqw] border-r-[.7cqw] border-t-[.7cqw] border-[#005c35]" /><div className="relative h-full overflow-hidden border border-[#004b2c]"><img src={imagePreview || ''} alt="Builder" className="h-full w-full object-cover saturate-[.85] contrast-110" style={{ display: imagePreview ? 'block' : 'none' }} /><div className={`absolute inset-0 flex items-center justify-center bg-[#d8c414] hh-mono text-[3cqw] text-[#005c35] ${imagePreview ? 'hidden' : ''}`}>UPLOAD PHOTO</div><span className="absolute bottom-0 left-1/2 -translate-x-1/2 translate-y-[48%] whitespace-nowrap border border-[#005c35] bg-yellow-300 px-[4%] py-[2%] hh-mono text-[2.1cqw] font-bold text-[#005c35]">VERIFIED</span></div></div>
    <div className="absolute left-[8%] right-[8%] top-[66%] text-center"><p className="hh-mono text-[2.6cqw] font-bold uppercase text-pink-400">{title}</p><h3 className="mt-[2%] break-words font-sans text-[7.4cqw] font-black uppercase leading-[.88] tracking-[-.045em] text-yellow-100">{name || 'ANONYMOUS BUILDER'}</h3><p className="mt-[3%] hh-mono text-[3.1cqw] font-bold text-yellow-300">@{(name || 'builder').trim().replace(/\s+/g, '').toLowerCase()} </p><span className="mt-[4%] inline-block border border-yellow-300/60 px-[5%] py-[2%] hh-mono text-[2.7cqw] text-yellow-100">STACK: {role || '—'}</span></div>
    <div className="absolute bottom-[4%] left-[6%] right-[6%] flex items-end justify-between border-t border-yellow-300/50 pt-[3%]"><div><p className="hh-mono text-[1.7cqw] text-yellow-100/70">SERIAL VERIFICATION ID</p><p className="hh-mono text-[2.6cqw] font-bold text-yellow-300">{serial}</p><div className="mt-[2%] h-[3cqw] w-[15cqw] opacity-80" style={{ background: 'repeating-linear-gradient(90deg,#ffe11a 0 2px,transparent 2px 4px,#ffe11a 4px 7px,transparent 7px 9px)' }} /></div><div className="text-right"><p className="mb-[1%] hh-mono text-[3cqw] font-bold text-yellow-100">#FrameInGoa</p><p className="hh-mono text-[1.8cqw] text-yellow-300">hhgoa.com</p></div><div className="text-right"><div className="ml-auto grid w-[9cqw] grid-cols-5 gap-[.35cqw] border border-yellow-300 p-[.7cqw]">{Array.from({ length: 25 }, (_, index) => <i key={index} className={`${[0, 1, 4, 6, 7, 10, 12, 13, 16, 18, 20, 21, 24].includes(index) ? 'bg-yellow-300' : ''} aspect-square`} />)}</div></div></div>
    <div ref={glareRef} className="builder-card-glare pointer-events-none absolute inset-0" />
  </article>
}
export default BuilderCard
