const loadImage = src => new Promise((resolve, reject) => { const image = new Image(); image.onload = () => resolve(image); image.onerror = reject; image.src = src })
const cover = (ctx, image, x, y, width, height) => { const scale = Math.max(width / image.width, height / image.height); const w = image.width * scale; const h = image.height * scale; ctx.drawImage(image, x + (width - w) / 2, y + (height - h) / 2, w, h) }
const fit = (ctx, text, max) => { let size = 72; ctx.font = `900 ${size}px Arial`; while (ctx.measureText(text).width > max && size > 30) { size -= 2; ctx.font = `900 ${size}px Arial` } return size }
export const downloadBuilderCard = async (imageDataUrl, { name, role, title }) => {
  const canvas = document.createElement('canvas'); canvas.width = 1080; canvas.height = 1350; const ctx = canvas.getContext('2d'); const y = '#ffe11a'; const g = '#004b2c'; const p = '#fb2784'; const safeName = name || 'ANONYMOUS BUILDER'; const serial = `HHG-2026-${String(safeName.split('').reduce((t, c) => t + c.charCodeAt(0), 247) % 9999).padStart(4, '0')}`
  ctx.fillStyle = g; ctx.fillRect(0, 0, 1080, 1350); ctx.strokeStyle = y; ctx.lineWidth = 5; ctx.strokeRect(12, 12, 1056, 1326); ctx.strokeStyle = p; ctx.lineWidth = 2; ctx.strokeRect(24, 24, 1032, 1302)
  ctx.textAlign = 'center'; ctx.fillStyle = y; ctx.font = '700 22px monospace'; ctx.fillText('B U I L D E R   P A S S', 540, 64); ctx.textAlign = 'right'; ctx.font = '900 16px monospace'; ctx.fillText('2:47 PM', 998, 58); ctx.fillText('STUDIO', 998, 78); ctx.textAlign = 'center'; ctx.font = '900 64px Arial'; ctx.fillText('HACKER  HOUSE', 540, 124); ctx.fillStyle = p; ctx.font = '900 52px Georgia'; ctx.fillText('गोवा', 540, 123); ctx.fillStyle = y; ctx.font = '700 21px monospace'; ctx.fillText('GOA, INDIA · 28—31 OCT 2026', 540, 160); ctx.strokeStyle = 'rgba(255,225,26,.6)'; ctx.lineWidth = 2; ctx.beginPath(); ctx.moveTo(70, 180); ctx.lineTo(1010, 180); ctx.stroke()
  const photo = await loadImage(imageDataUrl); ctx.fillStyle = p; ctx.fillRect(166, 225, 748, 748); ctx.fillStyle = y; ctx.fillRect(180, 239, 720, 720); cover(ctx, photo, 194, 253, 692, 692); ctx.fillStyle = y; ctx.fillRect(408, 953, 264, 40); ctx.fillStyle = g; ctx.font = '700 18px monospace'; ctx.fillText('VERIFIED', 540, 980)
  ctx.fillStyle = p; ctx.font = '700 24px monospace'; ctx.fillText((title || 'BUILDER').toUpperCase(), 540, 1040); ctx.fillStyle = y; const size = fit(ctx, safeName.toUpperCase(), 900); ctx.font = `900 ${size}px Arial`; ctx.fillText(safeName.toUpperCase(), 540, 1110); ctx.font = '700 27px monospace'; ctx.fillText(`@${safeName.replace(/\s+/g, '').toLowerCase()}`, 540, 1153); ctx.strokeStyle = y; ctx.strokeRect(360, 1175, 360, 48); ctx.font = '600 19px monospace'; ctx.fillText(`STACK: ${(role || '—').toUpperCase()}`, 540, 1207)
  ctx.textAlign = 'left'; ctx.font = '600 15px monospace'; ctx.fillText('SERIAL VERIFICATION ID', 68, 1270); ctx.font = '700 25px monospace'; ctx.fillText(serial, 68, 1304); for (let x = 68; x < 250; x += 12) { ctx.fillStyle = y; ctx.fillRect(x, 1317, x % 3 === 0 ? 7 : 4, 22) } ctx.textAlign = 'center'; ctx.font = '900 26px monospace'; ctx.fillText('#FrameInGoa', 675, 1300); ctx.font = '600 14px monospace'; ctx.fillText('hhgoa.com', 675, 1324)
  const blob = await new Promise(resolve => canvas.toBlob(resolve, 'image/png', 1)); if (!blob) throw new Error('Could not create image'); const url = URL.createObjectURL(blob); const link = document.createElement('a'); link.href = url; link.download = `HH-Goa-Builder-Pass-${safeName.replace(/[^a-z0-9]/gi, '-').toLowerCase()}.png`; link.click(); URL.revokeObjectURL(url)
}
